/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    gallery: Gallery;
    products: Product;
    tariffs: Tariff;
    fleet: Fleet;
    customers: Customer;
    leads: Lead;
    notifications: Notification;
    'gift-certificates': GiftCertificate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tariffs: TariffsSelect<false> | TariffsSelect<true>;
    fleet: FleetSelect<false> | FleetSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'gift-certificates': GiftCertificatesSelect<false> | GiftCertificatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Доступ только у администраторов. Менеджеры работают в разделе CRM.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Менеджер видит только заявки, клиентов и уведомления.
   */
  role: 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Раздел отключён в админке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  category: 'atv' | 'routes' | 'nature' | 'night' | 'manor';
  published?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Карточки услуг с фото, описанием, SEO и UTM-метками.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Например: zelenoe-ozero
   */
  slug: string;
  type: 'route' | 'tariff' | 'night' | 'fleet' | 'service' | 'other';
  shortDescription?: string | null;
  description?: string | null;
  price?: number | null;
  /**
   * Например: за квадроцикл / за двоих
   */
  priceNote?: string | null;
  published?: boolean | null;
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  duration?: string | null;
  distance?: string | null;
  difficulty?: ('easy' | 'medium' | 'hard') | null;
  /**
   * Только для маршрутов с разблокировкой
   */
  progressOrder?: number | null;
  audience?: string | null;
  /**
   * Мета-теги для поисковиков и соцсетей
   */
  seo?: {
    /**
     * До ~60 символов. Если пусто — берётся заголовок.
     */
    metaTitle?: string | null;
    /**
     * До ~160 символов.
     */
    metaDescription?: string | null;
    /**
     * Через запятую
     */
    metaKeywords?: string | null;
    /**
     * Картинка для соцсетей (1200×630)
     */
    ogImage?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * Подставляются в ссылки бронирования и рекламные URL
   */
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
    term?: string | null;
  };
  /**
   * Пишется в заявку при кнопке «Забронировать» с карточки товара
   */
  bookingSource?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Тексты страницы сверху, карточки тарифов ниже.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs".
 */
export interface Tariff {
  id: number;
  /**
   * Например: Зелёное озеро
   */
  title: string;
  /**
   * Стандарт / Премиум / Премиум+ / Легенда
   */
  badge?: string | null;
  /**
   * Короткий текст на карточке
   */
  description: string;
  /**
   * Например: для новичков
   */
  audience?: string | null;
  price: number;
  /**
   * Например: за двоих
   */
  priceNote?: string | null;
  /**
   * Например: 1,5 часа
   */
  duration: string;
  /**
   * 60 / 90 / 120 / 180
   */
  durationMinutes: number;
  distance: string;
  /**
   * Лёгкий / Средний / Сложный
   */
  difficultyLabel: string;
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * 1 = первый маршрут, 2 = следующий…
   */
  progressOrder?: number | null;
  /**
   * Например /images/routes/....jpg
   */
  imageUrl?: string | null;
  cover?: (number | null) | Media;
  imageAlt: string;
  /**
   * Не меняйте без нужды. Например: zelenoe-ozero
   */
  slug: string;
  /**
   * Меньше число — выше в списке
   */
  sortOrder?: number | null;
  season?: ('atv' | 'snow' | 'all' | 'future' | 'off') | null;
  activeForBooking?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Тексты страницы сверху, карточки техники ниже.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet".
 */
export interface Fleet {
  id: number;
  /**
   * Например: Капитан
   */
  name: string;
  /**
   * Грязь / прогулочный / …
   */
  role: string;
  color: string;
  drive: string;
  count: number;
  seats: number;
  /**
   * Например /images/fleet/....jpg
   */
  imageUrl?: string | null;
  cover?: (number | null) | Media;
  imageAlt: string;
  /**
   * Не меняйте без нужды. Например: kapitan
   */
  slug: string;
  /**
   * Меньше число — выше в списке
   */
  sortOrder?: number | null;
  season?: ('atv' | 'snow' | 'all' | 'future' | 'off') | null;
  activeForBooking?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Карточка гостя и прогресс маршрутов для записи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  /**
   * 0 — новичок · 1 — озеро → Памятник · 2 → Родник · 3 → Экспедиция · 4 — всё пройдено.
   */
  completedThrough?: number | null;
  notes?: string | null;
  lastLeadAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Очередь записей. Статус «Закрыта» открывает клиенту следующий маршрут. Ночные — без слота.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  customer?: (number | null) | Customer;
  /**
   * Менеджер, который взял заявку себе.
   */
  assignee?: (number | null) | User;
  name: string;
  phone: string;
  /**
   * Ночная — без календарного слота, дату согласуют в переписке.
   */
  bookingKind?: ('day' | 'night') | null;
  /**
   * Для ночных может быть пусто.
   */
  dateKey?: string | null;
  timeSlot?: ('10:00' | '12:00' | '14:00' | '16:00' | '18:00' | '20:00') | null;
  /**
   * Для дневных: 60 / 90 / 120 / 180.
   */
  durationMinutes?: number | null;
  /**
   * WhatsApp / Telegram / звонок — для ночных заявок.
   */
  contactPrefer?: string | null;
  date?: string | null;
  guests?: number | null;
  /**
   * В группе есть дети от 6 лет.
   */
  hasChildren?: boolean | null;
  route?: string | null;
  tariff?: string | null;
  /**
   * Гость указывает при записи — чтобы не ставить опытного на «Зелёное озеро».
   */
  riderExperience?: ('novice' | 'experienced' | 'regular') | null;
  message?: string | null;
  source?: string | null;
  pageUrl?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
    term?: string | null;
  };
  /**
   * «Закрыта» — заезд состоялся, клиенту открывается следующий маршрут.
   */
  status?: ('new' | 'in_progress' | 'confirmed' | 'done' | 'cancelled' | 'spam') | null;
  product?: (number | null) | Product;
  notifiedAt?: string | null;
  notifyError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * История сообщений о новых заявках. Скрыто, пока Telegram/почта не подключены.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  type: 'lead_created';
  channel: 'telegram' | 'email' | 'log';
  status: 'pending' | 'sent' | 'error';
  payload?: string | null;
  error?: string | null;
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * Именные сертификаты с уникальной публичной ссылкой.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-certificates".
 */
export interface GiftCertificate {
  id: number;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  /**
   * Публичная страница: /sertifikat/{slug}
   */
  slug: string;
  routeSlug: string;
  routeTitle: string;
  status: 'active' | 'redeemed' | 'cancelled';
  validUntil?: string | null;
  createdBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'tariffs';
        value: number | Tariff;
      } | null)
    | ({
        relationTo: 'fleet';
        value: number | Fleet;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'gift-certificates';
        value: number | GiftCertificate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  priceNote?: T;
  published?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  duration?: T;
  distance?: T;
  difficulty?: T;
  progressOrder?: T;
  audience?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
      };
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        term?: T;
      };
  bookingSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs_select".
 */
export interface TariffsSelect<T extends boolean = true> {
  title?: T;
  badge?: T;
  description?: T;
  audience?: T;
  price?: T;
  priceNote?: T;
  duration?: T;
  durationMinutes?: T;
  distance?: T;
  difficultyLabel?: T;
  difficulty?: T;
  progressOrder?: T;
  imageUrl?: T;
  cover?: T;
  imageAlt?: T;
  slug?: T;
  sortOrder?: T;
  season?: T;
  activeForBooking?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet_select".
 */
export interface FleetSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  color?: T;
  drive?: T;
  count?: T;
  seats?: T;
  imageUrl?: T;
  cover?: T;
  imageAlt?: T;
  slug?: T;
  sortOrder?: T;
  season?: T;
  activeForBooking?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  completedThrough?: T;
  notes?: T;
  lastLeadAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  customer?: T;
  assignee?: T;
  name?: T;
  phone?: T;
  bookingKind?: T;
  dateKey?: T;
  timeSlot?: T;
  durationMinutes?: T;
  contactPrefer?: T;
  date?: T;
  guests?: T;
  hasChildren?: T;
  route?: T;
  tariff?: T;
  riderExperience?: T;
  message?: T;
  source?: T;
  pageUrl?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        term?: T;
      };
  status?: T;
  product?: T;
  notifiedAt?: T;
  notifyError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  type?: T;
  channel?: T;
  status?: T;
  payload?: T;
  error?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-certificates_select".
 */
export interface GiftCertificatesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  slug?: T;
  routeSlug?: T;
  routeTitle?: T;
  status?: T;
  validUntil?: T;
  createdBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Включение календаря и вместимость слота. Остановки дней — в разделе Календарь → Остановка.
   */
  booking?: {
    enabled?: boolean | null;
    /**
     * Сколько отдельных заявок можно принять на одно время (например 14:00). По умолчанию 3.
     */
    slotCapacity?: number | null;
    /**
     * Старты 10:00–20:00. Занятость — интервал [старт, старт+durationMinutes), capacity пересечений.
     */
    slotHint?: string | null;
    /**
     * Правится в Календарь → Остановка.
     */
    closedRanges?:
      | {
          from: string;
          to: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Правится в Календарь → Остановка.
     */
    closedDates?:
      | {
          date: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Влияет на показ тарифов и техники (квадро / снег / пауза). Баннер на сайте отключён.
   */
  season?: {
    current?: ('atv' | 'snow' | 'pause') | null;
    label?: string | null;
    bannerText?: string | null;
  };
  /**
   * Тексты и медиа первого экрана главной. Картинку/видео можно заменить файлом.
   */
  pageHome?: {
    /**
     * Сейчас на сайте: «Премиальный отдых на природе»
     */
    eyebrow?: string | null;
    /**
     * Сейчас на сайте: «Погрузись в атмосферу» (например: Прокат)
     */
    titleLine1?: string | null;
    /**
     * Сейчас на сайте: «аристократа с»
     */
    titleLine2?: string | null;
    /**
     * Сейчас на сайте: «Вольница — место, где история усадеб встречается
     * с духом настоящего приключения.»
     */
    tagline?: string | null;
    /**
     * Превью и кнопка «Заменить фотографию». Путь — запасной вариант.
     */
    imageUrl?: string | null;
    /**
     * Если задана — имеет приоритет над путём.
     */
    cover?: (number | null) | Media;
    imageAlt?: string | null;
    /**
     * MP4/WebM. Если задано — играет вместо статичной картинки.
     */
    heroVideoUrl?: string | null;
    /**
     * Приоритет над путём к видео.
     */
    heroVideo?: (number | null) | Media;
    /**
     * Сейчас: «Смотреть уровни →»
     */
    primaryCtaLabel?: string | null;
    /**
     * Сейчас: «Записаться»
     */
    secondaryCtaLabel?: string | null;
    /**
     * Для гостей, которые уже катались — видно сразу под кнопками.
     */
    experienceHint?: string | null;
    /**
     * Сейчас: Не часы — уровни 1→4 · Новичок → Зелёное озеро · Опыт — доступ к сложным · 25–30 мин от Казани
     */
    facts?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Править панелью над списком Тарифы.
   */
  pageTariffs?: {
    /**
     * Сейчас на сайте: «Тарифы и услуги»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Выберите формат приключения»
     */
    subtitle?: string | null;
    /**
     * Сейчас на сайте: «Цена указана за клиентский квадроцикл. В группе резервируется машина инструктора.»
     */
    description?: string | null;
    /**
     * Справа — превью. Можно указать путь или загрузить файл ниже.
     */
    imageUrl?: string | null;
    /**
     * Если загрузите файл — он заменит путь выше.
     */
    cover?: (number | null) | Media;
    /**
     * Сейчас: «Вид с квадроцикла на лесную тропу к каменному обелиску на закате»
     */
    imageAlt?: string | null;
    /**
     * Сейчас: Инструктор · Экипировка · Топливо · Маршрут
     */
    chips?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Сейчас: «Тарифы»
     */
    sectionLabel?: string | null;
    /**
     * Сейчас: «Тарифы»
     */
    sectionTitle?: string | null;
    /**
     * Сейчас: «Не можете выбрать?»
     */
    ctaTitle?: string | null;
    /**
     * Сейчас: «Подскажем тариф под опыт и состав группы.»
     */
    ctaText?: string | null;
  };
  /**
   * Править панелью над списком Техника.
   */
  pageFleet?: {
    /**
     * Сейчас на сайте: «Наша техника»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Мощные. Надёжные. Готовые к приключениям»
     */
    subtitle?: string | null;
    /**
     * Сейчас на сайте: «На старте 8 квадроциклов: 4 грязевых и 4 прогулочных. Перед каждым выездом — подготовка, ТО и инструктаж.»
     */
    description?: string | null;
    /**
     * Справа — превью. Можно указать путь или загрузить файл ниже.
     */
    imageUrl?: string | null;
    /**
     * Если загрузите файл — он заменит путь выше.
     */
    cover?: (number | null) | Media;
    /**
     * Сейчас: «Ряд грязных квадроциклов на каменистой тропе перед освещённой деревянной усадьбой»
     */
    imageAlt?: string | null;
    /**
     * Сейчас: Подготовка · ТО и осмотр · Экипировка · Подбор под маршрут
     */
    chips?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Сейчас: «Наш парк»
     */
    sectionLabel?: string | null;
    /**
     * Сейчас: «8 единиц на старте»
     */
    sectionTitle?: string | null;
    /**
     * Сейчас: «Не знаете, что выбрать?»
     */
    ctaTitle?: string | null;
    /**
     * Сейчас: «Подберём технику под опыт и маршрут. В группе — машина инструктора.»
     */
    ctaText?: string | null;
  };
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKeywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Скрыто в админке. Тексты первого экрана задаются в коде/дефолтах.
   */
  galleryIntro?: {
    /**
     * Сейчас: «Галерея»
     */
    title?: string | null;
    /**
     * Сейчас: «Атмосфера свободы и приключений»
     */
    subtitle?: string | null;
    /**
     * Сейчас: «Живые кадры с маршрутов и базы Вольницы. Новые фото можно добавлять через CMS.»
     */
    description?: string | null;
  };
  /**
   * Скрыто, пока Telegram/почта не подключены.
   */
  notify?: {
    /**
     * Настраивается администратором на сервере.
     */
    channelHint?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  booking?:
    | T
    | {
        enabled?: T;
        slotCapacity?: T;
        slotHint?: T;
        closedRanges?:
          | T
          | {
              from?: T;
              to?: T;
              note?: T;
              id?: T;
            };
        closedDates?:
          | T
          | {
              date?: T;
              note?: T;
              id?: T;
            };
      };
  season?:
    | T
    | {
        current?: T;
        label?: T;
        bannerText?: T;
      };
  pageHome?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        tagline?: T;
        imageUrl?: T;
        cover?: T;
        imageAlt?: T;
        heroVideoUrl?: T;
        heroVideo?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        experienceHint?: T;
        facts?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  pageTariffs?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        imageUrl?: T;
        cover?: T;
        imageAlt?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        sectionLabel?: T;
        sectionTitle?: T;
        ctaTitle?: T;
        ctaText?: T;
      };
  pageFleet?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        imageUrl?: T;
        cover?: T;
        imageAlt?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        sectionLabel?: T;
        sectionTitle?: T;
        ctaTitle?: T;
        ctaText?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
      };
  galleryIntro?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
      };
  notify?:
    | T
    | {
        channelHint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}